version: 2.1

with_python: &with_python
  docker:
    - image: circleci/python:3.7

install_poetry: &install_poetry
  run:
    name: Install Poetry
    command: |
      pip install poetry==1.2.0a1
      poetry --version

install_python_deps: &install_python_deps
  run:
    name: Install python dependencies
    command: poetry install --no-ansi --no-interaction

show_versions: &show_versions
  run:
    name: Show versions
    command: poetry show

jobs:
  main:
    <<: *with_python

    steps:
      - checkout

      - *install_poetry
      - run:
          name: Install python dependencies
          command: poetry install --no-ansi --no-interaction --extras obj
      - *show_versions

      - run:
          name: Clone submodule
          command: |
            git submodule sync
            git submodule update --init

      - run:
          name: Run tests
          when: always
          command: ./dev.py coverage

      - run:
          name: Run the doc build
          when: always
          command: ./dev.py doc

      - run:
          name: Test that the build runs
          when: always
          command: poetry build

  lint:
    <<: *with_python

    steps:
      - checkout

      - *install_poetry
      - run:
          name: Install python dependencies
          command: poetry install --no-ansi --no-interaction
      - *show_versions

      - run:
          name: Check lint
          when: always
          command: ./dev.py lint

  format:
    <<: *with_python

    steps:
      - checkout

      - *install_poetry
      - run:
          name: Install python dependencies
          command: poetry install --no-ansi --no-interaction
      - *show_versions

      - run:
          name: Check code format
          when: always
          command: ./dev.py black-check

workflows:
  version: 2

  on-commit:
    jobs:
      - main
      - lint
      - format

  daily:
    triggers:
      - schedule:
          cron: "0 17 * * *"
          filters:
            branches:
              only: main
    jobs:
      - main
      - lint
      - format
